### ISSUE TITLE
Application page cannot display more than 256 applications 

### ISSUE THREAD

**Issue by linhvuc8** [vmware-tanzu/kubeapps#4948] opened 2022-06-23 11:42 UTC
### Description:

Hi,

I found that the Kubeapps Application page is limited to show only 256 applications. One of my namespace has around 280 applications and it can only display the first 256 applications (ordered by alphabet). 

It seems that this limitation is due to the "helm list" command default maximum number of releases to fetch (default 256). Reference: https://helm.sh/docs/helm/helm_list/

When I try to run "helm list -m 300" from cli, I can get the full list of releases/applications

I tried to look up for the configuration options from the Bitnami helm chart at https://artifacthub.io/packages/helm/bitnami/kubeapps but there is no such settings available

So, Is there anyway to change this default value?

**Comment by absoludity** [comment] 2022-06-24 04:08
Thanks @linhvuc8 . We should be paginating through all the results anyway (using a combination of `--max` and `--offset` as described in the page you linked to), so it should not be needed as a setting, it should just work, but doesn't, so it's a genuine bug :)

**Comment by linhvuc8** [comment] 2022-06-24 07:57
okay thanks @absoludity !! Do you have a plan to fix it in any of the next versions?

**Comment by absoludity** [comment] 2022-06-26 23:44
I don't think it'll make it into our current release (in progress), but yes, we'll triage it in our next planning meeting and I'd expect it to be fixed in the following release.

**Comment by beni0888** [comment] 2022-08-03 16:03
I'm afraid I couldn't reproduce this bug. I've performed a test by creating 283 applications in the default namespace, and Kubeapps dashboard is actually showing the whole list of 283 apps.

**Comment by beni0888** [comment] 2022-08-04 10:16
@linhvuc8 Could you provide more context/information (kubeapps setup, etc) that help us to reproduce the issue?

**Comment by ppbaena** [comment] 2022-09-07 07:17
Close this issue as maintainers team cannot reproduce it. 
Feel free to re-open this issue in case you can reproduce it (providing steps and configuration to reproduce the issue).

**Closed by ppbaena** 2022-09-07 07:17 UTC
Labels: kind/bug, component/plugin-helm
