### ISSUE TITLE
Support for array variables

### ISSUE THREAD

**Issue by asanCar** [vmware-tanzu/kubeapps#1715] opened 2020-05-04 14:29 UTC
We're currently using kubeapps v1.10.0 and trying to use the form UI to fill array variables in Helm's values YAML file.

We are trying to reproduce some of the examples exposed in [https://rjsf-team.github.io/react-jsonschema-form/](https://rjsf-team.github.io/react-jsonschema-form/) but they doesn't work.

The form takes the whole array JSON definition as an String in a InputText form, as shown in the image:
![form](https://user-images.githubusercontent.com/15346506/80976989-6bfe0d80-8e24-11ea-86df-058903cb4bde.png)

We have found the array form component imported in the project [kubeapps/dashboard/src/components/SchemaForm/ArrayFieldTemplate.tsx](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/SchemaForm/ArrayFieldTemplate.tsx) but it doen't seem to work.

Is this feature supported?

**Comment by andresmgot** [comment] 2020-05-04 17:10
Hello @asanCar, unfortunately arrays are not supported yet. We are not using react-jsonschema-form for that form to provide a custom experience (like sliders). We have a bit of documentation for that here: https://github.com/kubeapps/kubeapps/blob/a051785e36bab308776f948c1d9f84594c8434c0/docs/developer/basic-form-support.md

In any case, arrays are something that we want to support. I am not sure if it would be possible to delegate some rendering to `react-jsonschema-form` or if we would need to build a component for arrays the same way we do for sliders and booleans... Would you or someone from your team able to contribute? That would speed up the process.

**Comment by mecampbellsoup** [comment] 2021-01-28 23:42
> Hello @asanCar, unfortunately arrays are not supported yet. We are not using react-jsonschema-form for that form to provide a custom experience (like sliders). We have a bit of documentation for that here: [`a051785`/docs/developer/basic-form-support.md](https://github.com/kubeapps/kubeapps/blob/a051785e36bab308776f948c1d9f84594c8434c0/docs/developer/basic-form-support.md)
> 
> In any case, arrays are something that we want to support. I am not sure if it would be possible to delegate some rendering to `react-jsonschema-form` or if we would need to build a component for arrays the same way we do for sliders and booleans... Would you or someone from your team able to contribute? That would speed up the process.

Hi @andresmgot - we would be in a position to throw some developer resources at this, as we are planning to fork the repo and add `react-jsonschema-form`. However we have some questions on the best approach - should we discuss here?

**Comment by andresmgot** [comment] 2021-01-29 09:20
hi @mecampbellsoup, yes, happy to help as much as I can :) If we can merge that feature in this repo it would be great.

**Comment by mecampbellsoup** [comment] 2021-01-29 13:41
@andresmgot our developers @aanthonyrizzo and @YitzyD are in the planning phase right now. I'll have them jump in to this thread.

**Comment by andresmgot** [comment] 2021-01-29 17:14
Great to hear! No, there is nothing else apart from the things linked in this thread.

**Comment by aanthonyrizzo** [comment] 2021-01-29 19:17
Hi ! So I've spent the last day or so looking at the current form implementation and trying to come up with a roadmap for an implementation. We love the idea of using `react-jsonschema-form` because of its flexibility and its ability to support basically anything. The only problem that I see using it is we will have to maintain 2 states. The `react-jsonschema-form` keeps a state attribute called formData which stores all of the forms values but its seems like the current form uses the `DeploymentForm`'s state as the source of truth and that is what is send to kubeops. Im assuming you guys decided to use the YAML string in state instead of a JSON to preserve the comments in the YAML files. So we would probably need an onChange handler for the form to update the YAML state and I'm not sure how we feel about a pattern like this. What are your thoughts @andresmgot ?

**Comment by andresmgot** [comment] 2021-02-01 08:57
Thanks @aanthonyrizzo for taking a look! From the top of my mind, we may have two options here:

 - Migrate all the current features to use `react-jsonschema-form` only.
 - Keep the current code and use `react-jsonschema-form` only for arrays. Maybe we can define a standalone form just with this field.

The first may be a cleaner option but I am not sure if it would cover all the use cases we have now (and it would be a much bigger effort). With the second option, I am sure we would need to add some glue code to behave as you mention. I am okay with that.

As soon as you have some working code, even if it's not finished, we can discuss over the code.

**Comment by aanthonyrizzo** [comment] 2021-02-01 15:48
I really would like to get this to work as a full `react-jsonschema-form` so I think I'm going to try that first and I will open a PR if I think it can work. Thanks for you input @andresmgot

**Comment by mecampbellsoup** [comment] 2021-02-01 16:23
> I really would like to get this to work as a full `react-jsonschema-form` so I think I'm going to try that first and I will open a PR if I think it can work. Thanks for you input @andresmgot

My (probably uninformed) opinion is it would be better to implement just arrays to use `react-jsonschema-form`. It sounds like much more work to me to overhaul all currently supported features and components to use it and doing so doesn't necessarily add value.

A total swapout of the current library for `react-jsonschema-form` can be a long-running/ongoing feature.

**Comment by andresmgot** [comment] 2021-02-01 17:23
I agree with @mecampbellsoup. Migrating everything to `react-jsonschema-form` may be an unnecessary effort for achieving the goal here (unless some major blocker is found). 

My concern is that, even if you had the time to do the migration to `react-jsonschema-form`, you may find things that cannot be migrated (e.g. the current sliders) and we would need to include "regressions" or breaking changes.

**Comment by aanthonyrizzo** [comment] 2021-02-01 17:44
As I keep digging I am tending to agree as well. Since all of the form parameters are rendered by [Param.tsx](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Param.tsx) I think integrating `react-jsonschema-form` would be a very large project and would take more than one person a good deal of time. 

As for creating the "Array" only case,  it would not work since the library wants to create a `<form/>` html object which would result in nested `<form/>` tags (top level one here)[https://github.com/kubeapps/kubeapps/blob/1c9c6b5caaf92c7ce6eb3af8110c7ca73e62b81f/dashboard/src/components/DeploymentForm/DeploymentForm.tsx#L150] so it would have to be an all in integration if we want to use this particular form library (at least from my perspective/understanding).

**Comment by andresmgot** [comment] 2021-02-02 09:10
I see, we may need to implement the functionality ourselves then.

**Comment by danoo** [comment] 2021-02-09 11:06
@aanthonyrizzo @mecampbellsoup I think it would be good to chat to gather and better understand your requirements. Can you please ping me or Andres on slack?

**Comment by ppbaena** [comment] 2022-06-09 08:22
To be closed as it is not included in the current roadmap for Kubeapps. Could be re-opened if more demand on this issue.

**Closed by ppbaena** 2022-06-09 08:22 UTC
Labels: kind/feature, component/ui

**Comment by jgagnon44** [comment] 2024-05-07 17:20
I am attempting to set the chart values into Kubeapps via the YAML editor, not the UI. When I attempt to deploy, it emits a generic error that tells me nothing - just that an error occurred. I eventually went back to an older chart that did not have the new values I was trying out and it successfully deployed. It turns out the new values I was trying to add has array data in the YAML. This seems very related to this issue. Is it still the case that Kubeapps does not support values YAML with arrays?
