### ISSUE TITLE
possible backward incompatible change between 8.0.15 and 8.0.16

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4691] opened 2022-05-12 01:11 UTC
the change to the chart's values.yaml between 8.0.15 and 8.0.16 is a possible backward incompatible change.

the values file changed from something like:
```
postgresql:
  enabled: true
  auth:
    password: ""
```

to 
```
postgresql:
  enabled: true
  auth:
    postgresPassword: ""
```

as a user, i created a values.yaml file which provided a password using "postgres.auth.password" and installed kubeapps at a version prior to 8.0.16
i then re-installed kubeapps at the latest 8.0.17 and kubeapps stopped working due to issue #4689 as the password were not matching anymore.

**Comment by absoludity** [comment] 2022-05-12 03:17
Right, I'm guessing that, as you mention in the last sentence above, the issue you hit was caused by a persistent volume as in #4689 , and unrelated to the change you've identified above.

Kubeapps was not even using `postgresql.auth.password`(the non-admin user password)  in any deployments, it has always used `postgresql.auth.postgresPassword` (or formally `postgresql.auth.postgresqlPassword`). The values.yaml accidentally changed to `postgresql.auth.password` as part of an upstream change as documented at https://github.com/bitnami/charts/pull/10006 .

As outlined there, I believe we could switch to use the non-admin postgres user, but that's unrelated to this issue (and may not be worthwhile if we replace postgresql with redis anyway).

I'll close this for now, but please re-open it if you can provide steps to reproduce showing it is related to this change (ie. create a secret yourself with both passwords set, then use the `existingSecret` option so that the postgres chart won't generate one for itself, then see if you can reproduce the issue).

Thanks!

**Closed by absoludity** 2022-05-12 03:17 UTC
Labels: kind/bug

**Comment by dlaloue-vmware** [comment] 2022-05-12 04:25
I had not realized that the switch to password was in fact a regression (i thought it was about using a consistent naming across the kubeapps chart).
in light of this, i agree we can just close this issue.
