### ISSUE TITLE
Unable to list apps Error while fetching related charts: pq: relation

### ISSUE THREAD

**Issue by vijimgowda** [vmware-tanzu/kubeapps#5624] opened 2022-11-09 12:56 UTC
**Summary**
not able to list any charts after logging in using token 

after installation of helm  chart kubeapps   ( chart version -12.0.0 , app version   2.6.0 ) generated token as per the procedure but not able to list apps 

steps followed 

 helm repo add bitnami https://charts.bitnami.com/bitnami
 helm install -n kubeapps --create-namespace kubeapps bitnami/kubeapps
kubectl create --namespace default serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator

create secret using below 
 cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Secret
  metadata:
    name: kubeapps-operator-token
    namespace: default
    annotations:
      kubernetes.io/service-account.name: kubeapps-operator
  type: kubernetes.io/service-account-token
  EOF

 kubectl get --namespace default secret kubeapps-operator-token -o go-template='{{.data.token | base64decode}}'

**Comment by antgamdia** [comment] 2022-11-09 13:28
Hi @vijimgowda , thanks for using Kubeapps! Sorry yo hear you're facing some issues during the deployment.
This error is simply caused by the PostgreSQL not being initialized when starting Kubeapps. Given that you're using the default configuration (that is, you aren't passing any `values.yaml` file), Kubeapps will try to add the Bitnami Application Catalog repository.

I'd bet there is an error while connecting to the repo, and therefore, it is not able to create the database tables.
Please, share the output of `kubectl get pods -n kubeapps` and the logs from the pod starting with `apprepo-kubeapps-sync-bitnami--`

**Comment by vijimgowda** [comment] 2022-11-11 04:56
@antgamdia  thank you for your response and 
that is, you aren't passing any values.yaml file>>> yes i am passing custom-values file with enabling ingress with DNS value.
ingress:
  enabled: true
  hostname: www.dns-value.com
  path: /kubeapps
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    kubernetes.io/ingress.class: nginx
frontend:
  replicaCount: 1
dashboard:
  replicaCount: 1
apprepository:
  initialRepos: []
  crontab: "*/10 * * * *"
  replicaCount: 1
kubeops:
  replicaCount: 1
assetsvc:
  replicaCount: 1 
  
Please, share the output of kubectl get pods -n kubeapps >>>>

~/kubeapps$ kubectl get po -n kubeapps
NAME                                                          READY   STATUS    RESTARTS   AGE
kubeapps-7c47dcc4b6-qg2mb                                                        1/1          Running   0          13m
kubeapps-internal-apprepository-controller-5f64b9b9bd-z424w   1/1         Running   0          13m
kubeapps-internal-dashboard-5f7b686dbf-sjls5                              1/1         Running   0          13m
kubeapps-internal-kubeappsapis-789f5bc96d-rxbxf                        1/1         Running   0          13m
kubeapps-internal-kubeappsapis-789f5bc96d-w2b6x                      1/1         Running   0          13m
kubeapps-postgresql-0                                                                       1/1        Running   0          13m


 logs from the pod starting with apprepo-kubeapps-sync-bitnami--

 kubectl logs -f kubeapps-internal-apprepository-controller-5f64b9b9bd-l8wfb -n kubeapps
I1111 04:53:30.777229       1 root.go:34] apprepository-controller has been configured with: server.Config{APIServerURL:"", Kubeconfig:"", RepoSyncImage:"docker.io/bitnami/kubeapps-asset-syncer:2.6.0-scratch-r2", RepoSyncImagePullSecrets:[]string(nil), ImagePullSecretsRefs:[]v1.LocalObjectReference(nil), RepoSyncCommand:"/asset-syncer", KubeappsNamespace:"kubeapps", GlobalPackagingNamespace:"kubeapps", DBURL:"kubeapps-postgresql:5432", DBUser:"postgres", DBName:"assets", DBSecretName:"kubeapps-postgresql", DBSecretKey:"postgres-password", UserAgentComment:"kubeapps/2.6.0", Crontab:"*/10 * * * *", TTLSecondsAfterFinished:"3600", ReposPerNamespace:true, CustomAnnotations:[]string{""}, CustomLabels:[]string{""}, ParsedCustomAnnotations:map[string]string{}, ParsedCustomLabels:map[string]string{}}
W1111 04:53:30.778808       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1111 04:53:30.812618       1 controller.go:114] Creating event broadcaster
I1111 04:53:30.821754       1 controller.go:132] Setting up event handlers
I1111 04:53:30.821863       1 controller.go:174] Starting AppRepository controller
I1111 04:53:30.821887       1 controller.go:177] Waiting for informer caches to sync
I1111 04:53:30.826970       1 reflector.go:219] Starting reflector *v1.CronJob (0s) from pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167
I1111 04:53:30.827021       1 reflector.go:255] Listing and watching *v1.CronJob from pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167
I1111 04:53:30.827079       1 reflector.go:219] Starting reflector *v1alpha1.AppRepository (0s) from pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167
I1111 04:53:30.827111       1 reflector.go:255] Listing and watching *v1alpha1.AppRepository from pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167
I1111 04:53:30.922571       1 controller.go:182] Starting workers
I1111 04:53:30.922597       1 controller.go:188] Started workers

**Comment by vijimgowda** [comment] 2022-11-15 06:31
any updates ????

**Comment by ppbaena** [comment] 2022-11-21 10:52
Assigned to take a look at this iteration.

**Comment by absoludity** [comment] 2022-11-22 02:44
Hi there @vijimgowda . It looks like you don't have any repositories specified? That is, your list of pods:

```
> ~/kubeapps$ kubectl get po -n kubeapps
> NAME READY STATUS RESTARTS AGE
> kubeapps-7c47dcc4b6-qg2mb 1/1 Running 0 13m
> kubeapps-internal-apprepository-controller-5f64b9b9bd-z424w 1/1 Running 0 13m
> kubeapps-internal-dashboard-5f7b686dbf-sjls5 1/1 Running 0 13m
> kubeapps-internal-kubeappsapis-789f5bc96d-rxbxf 1/1 Running 0 13m
> kubeapps-internal-kubeappsapis-789f5bc96d-w2b6x 1/1 Running 0 13m
> kubeapps-postgresql-0 1/1 Running 0 13m
```

does not even include an `apprepo-kubeapps-sync-bitnami-..` pod. When Antonio requested:

> I'd bet there is an error while connecting to the repo, and therefore, it is not able to create the database tables.
> Please, share the output of `kubectl get pods -n kubeapps` and the logs from the pod starting with `apprepo-kubeapps-sync-bitnami--`

what we were after is the logs of a specific pod that is created to sync your repository (which also happens to create the database tables). But the logs you provided are for the actual controller, not the sync job, but nonetheless helpful, as they also appear to show that there are no app repositories installed. Can you please paste the output of the following:

```
kubectl get apprepositories -A
```

Thanks.

**Comment by ppbaena** [comment] 2022-12-19 10:46
To be closed as no more feedback. Please re-open if necessary.

**Closed by ppbaena** 2022-12-19 10:46 UTC
Labels: awaiting-more-evidence
