### ISSUE TITLE
[carvel] `GetInstalledPackageResourceRefs` fails behind contour

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#4614] opened 2022-04-25 18:21 UTC
### Description:

When using Contour (h2c, `application/grpc-web+proto`, just token-based login) `GetInstalledPackageResourceRefs` seems to fail for Carvel packages.
Specifically, I've been able to identify two scenarios: i) an OK package; ii) an unreconciled package.
While for i) the error really visible, in ii) it is navigation-breaking.

#### Case i)

In this scenario, there's no visible error, but the console shows:

![image](https://user-images.githubusercontent.com/11535726/165141333-c361a947-8ca7-4307-b0bf-84d66ee5d94e.png)

Note the error:

```console
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
```

#### Case ii)

![image](https://user-images.githubusercontent.com/11535726/165140452-6af32203-3604-444f-bf10-d08cd205e7eb.png)

This is consistent with an error on the server-side:

````console
I0425 17:12:04.722787       1 server.go:59] OK 413.7089ms /kubeappsapis.core.packages.v1alpha1.PackagesService/GetAvailablePackageDetail
I0425 17:12:18.095622       1 server.go:59] Internal 14.9762018s /kubeappsapis.core.packages.v1alpha1.PackagesService/GetInstalledPackageResourceRefs
````

Besides, it is a concerning error because the user actually see a "working" package (where they get notified about the non-reconcialtion cause):
![image](https://user-images.githubusercontent.com/11535726/165140902-dfdc8ddf-ccfd-4259-8e2e-f0d0d1c0397f.png)

But after the get resources timer get executed (in about 2 seconds or so), immediately the screen becomes:

![image](https://user-images.githubusercontent.com/11535726/165140707-41544fb4-a3a5-40e1-b4b3-00459818f216.png)

### Steps to reproduce the issue:

1.Install a Carvel package, ie. Contour
2. Wait until it fails to reconcile
3. Access the package details view
4. Wait for a couple of seconds

### Describe the results you received:

See above.

### Describe the results you expected:

Everything working fine or, if there is an actual error, at least do not wipe down the entire page already loaded.

### Additional information you deem important (e.g. issue happens only occasionally):

N/A

### Version of Helm, Kubeapps and Kubernetes:

N/A - "Kubeapps running behind Contour"

**Comment by absoludity** [comment] 2022-04-26 05:33
Thanks for the details @antgamdia . There seems to be two separate errors - the first one you've highlighted seems to be `GetResources` failing, while the second is `GetResourceRefs` (though they well may be related, since `GetResources` itself calls `GetResourceRefs` to ensure the request is valid).

I've just set up this environment locally to reproduce and tried installing the kubeapps carvel package (via Kubeapps :P )  in a test namespace. It seems to work without error (at least, your case 1), the `GetInstalledPackageResourceRefs` call is slow (15s) but working, as is the `GetResources`:

![kubeapps-get-resources](https://user-images.githubusercontent.com/497518/165227020-8564cfc1-9742-4fbf-bd2d-09050fb64f5a.png)

I haven't yet debugged why the server side events aren't used and so the page in this setup is defaulting to polling - that may help (and may be related).

Oddly, I could easily reproduce the second issue with the test carvel package:

![installed-pkg-resource-refs](https://user-images.githubusercontent.com/497518/165228364-3bd2a003-de09-4e37-8028-91928b045c3e.png)

I suspect what's happening there is that the grpc request is (or may be) hitting a context time limit and contour's grpc machinery is converting that to a 504 gateway timeout. Either way, I think the key here will be to debug and fix why `GetInstalledPackageResourceRefs` is, in this case, taking over 15s (for the kubeapps deployment, it was quick - under a second, so something is a little odd - perhaps I'll recheck those)

**Comment by absoludity** [comment] 2022-04-26 06:02
Right, I thought the 14.9999s looked a bit suspicious :P . From https://projectcontour.io/docs/v1.20.1/config/api/#projectcontour.io/v1.TimeoutPolicy

> Timeout for receiving a response from the server after processing a request from client. If not supplied, Envoy’s default value of 15s applies.

If I edit my `HTTPProxy` and add a `TimeoutPolicy` of 300s, for a failed install (your case 2), the `GetInstalledPackageResourceRefs` still fails at 300s, so it looks like we have an issue in the plugin there to fix.

So, in summary, I think your case 1 may be fixed by adding a timeout policy of 30s or something for the contour httpproxy route, but your case 2 is I think a valid bug in the code where the carvel plugin's endpoint appears not to return at all, as if we've got a condition there waiting for the initial condition (I do remember a conversation about that, turns out we can't). Let's fix that. I can take a look first thing tomorrow.



> I suspect what's happening there is that the grpc request is (or may be) hitting a context time limit and contour's grpc machinery is converting that to a 504 gateway timeout.

This wasn't correct, turned out it was just the envoy default of 15s before a response timeout unless you specify otherwise in your HTTPProxy route.

**Comment by absoludity** [comment] 2022-04-26 06:02
And either way, we need to improve the performance of that endpoint as it should *not* be taking that long either way (and would not have triggered an issue here if it was more performant).

**Comment by absoludity** [comment] 2022-04-27 04:47
The related PR #4623 fixes the case 2. I can't reproduce the case 1. In fact, with the linked change, the service side events work just fine too (until the Contour/Envoy timeout occurns, at which point the GetResources requestcloses and it opens another connection as expected).

**Closed** 2022-04-27 21:07 UTC
