### ISSUE TITLE
Recurring kubeappsapis OOM

### ISSUE THREAD

**Issue by cpotteck** [vmware-tanzu/kubeapps#4226] opened 2022-02-03 06:11 UTC
### Description:

We are seeing recurring OOM restarts on kubeappsapis pods when deploying or deleting releases on kubeapps. 
Both on bitnami/kubeapps chart versions `7.6.2` and `7.7.2`. Each deployment peaks memory usage which then drops slightly and settles at roughly 40 to 60 MiB higher than before the deployment, deletions also increase memory usage but by a lesser amount. After OOM, the memory usage stays stable at 25-30 MiB until more deployments/deletions are performed. This same pattern is visible on both replicas. See the following memory usage graph over 2 days for one of the replicas:

<img width="1120" alt="Screen Shot 2022-02-03 at 12 15 32 AM" src="https://user-images.githubusercontent.com/27770542/152285402-3c5de4d7-7f14-43f1-bde9-bdec77ed7b7d.png">

This screenshot shows a zoomed-in view of the last few hours of the graph above and shows the OOM restarts:
<img width="1277" alt="Screen Shot 2022-02-03 at 12 16 58 AM" src="https://user-images.githubusercontent.com/27770542/152285562-ea8784ff-6ca7-4396-a560-d4f12fd8297a.png">

I tested a scenario on a kubeapps instance already tracking a few releases, where I deployed and deleted the same chart repeatedly without touching existing releases, and ending the test by deleting all releases which were not existing at the start of the test. The memory usage was still consistently trending upwards and never dropped over the rest of the pod lifecycle.

These OOM restarts seem to correlate with a variety of error messages (some of which seem to be incomplete), users are seeing in their browser when attempting to deploy or delete. Here are a few examples:
```
An error occurred:
```
```
An error occurred: Response closed without headers
```
```
Unable to delete the application. Received:
```

We are aware of issues reported in https://github.com/kubeapps/kubeapps/issues/3567 and that it has been marked as resolved. As far as I can see, the fixes introduced to close that issue are included in chart version 15.6.2 and 15.7.2. 

### Steps to reproduce the issue:

1. Deploy bitnami/kubeapps chart version 7.6.2
2. Through kubeapps, deploy and delete applications using the same chart repeatedly until the memory usage is close to the limit
3. At this point, memory usage peaks during deploy/delete actions and drops slightly afterwards but not enough to compensate for increases. There is a slight decrease of memory usage over many hours (~1MB/hour from my observations, see attached graphs) but again this is not enough to prevent OOMs in our use case.
4. Continue deploying and deleting the same chart until the pod OOMs and restarts, there might be some errors in the browser correlating with this depending on timing.

### Describe the results you received:

The kubeappsapi pod is restarted due to OOM.

### Describe the results you expected:

I would expect memory usage to decrease at some point after deletion/creation operations have completed to avoid an OOM restart.

### Additional information you deem important (e.g. issue happens only occasionally):

- Our most used chart and the one for which we have faced the most issues relating to kubeappsapis OOMs deploys a Jenkins controller deployment and other resources, for a total of 5 pods.
- I have tried increasing memory limits, increasing aggressiveness of garbage collection via the `GOGC` variable, but this had either no effect or only delayed the OOM a little.
- Over the same time range shown in the memory usage graphs above, CPU usage stays relatively stable:
<img width="1228" alt="Screen Shot 2022-02-03 at 12 36 28 AM" src="https://user-images.githubusercontent.com/27770542/152287215-b7dad32e-f72f-467f-ac7b-4bf1f89d7875.png">

### kubeappsapis config for the bitnami/kubeapps chart
Note that we are using the default 2 replicas for kubeappsapis.
```yaml
  kubeappsapis:
    image:
      registry: eu.gcr.io
      repository: private-registry
    resources:
      limits:
        cpu: 250m
        memory: 312Mi
      requests:
        cpu: 50m
        memory: 256Mi
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:
(There are no releases managed by kubeapps in the kubeapps namespace)

```
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

- Output of `kubectl version`:

Note that this is in a GKE cluster.

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-gke.1300", GitCommit:"9352724e36d9c7c35609d30b2696b0de61d23aa0", GitTreeState:"clean", BuildDate:"2021-10-06T09:26:56Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment] 2022-02-03 12:34
Thanks for the detailed report. We have been trying to debug the issue and find the root cause of it, but still no 100% success.
In the meanwhile, we have been trying to mitigate it, for instance, adding more replicas by default and tweaking the GOGC var, as you already did.

I believe it is a problem also present in Helm (see https://github.com/helm/helm/pull/10486), so we are trying to update to the latest Helm's code available as soon as possible.
We are planning to release a new version soon, but, you can always give it a try to the `kubeapps/kubeapps-apis:latest` image, to see if bumping Helm to 3.8 reduces the OOM rate.

Anyway, as soon as we have some bandwidth to look at this issue more closely we will try to continue addressing it.
Any suggestion or help is always welcomed, though :P

**Comment by castelblanque** [comment] 2022-07-29 15:32
## Tested with chart version 10.0.2 (Kubeapps v2.4.6)

Tested with single and multiple replicas.

Kubeapps APIs
- No remarkable increases in memory
- Memory was freed quickly (saw a drop from 55Mi to 41Mi right after installing a package)
- After many deploys/updates/deletes never got an OOM nor pod restart. Memory might reach pods limits, but never producing the restart or recreation of pods.

## Tested with chart version 7.6.2 (Kubeapps v2.4.2)
- Same behavior in general terms
- Memory wasn't being released so quickly
- Never got OOM or restart

Closing the issue, please feel free to reopen if problem still persisting.

**Closed by castelblanque** 2022-07-29 15:32 UTC
Labels: kind/bug, component/apis-server
